<a href="https://colab.research.google.com/github/akanksha-parasar/File-Handling-in-Python/blob/main/NumpyExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Name:Akanksha Parasar

# Prn:1132210166


## Lab Session - 13

# 1. Consider this URL:
# https://numpy.org/doc/stable/user/absolute_beginners.html ,
# execute all the examples and write your observations.

In [1]:
!pip install numpy

Creation of arrays.

In [24]:
import numpy as np

#np.array to crate array using numpy
a = np.array([1,2,3,4,5,6])
print("At position 0:",a[0])
b = np.array([[1,2,3,4,5],[6,7,8],[9,10]])
print("At position 0:",b[0])
print("First element at pos 0:",b[0][0])

#np.zeros to create an array containing 0s
ZeroArray = np.zeros(5)
print("Array containing zeros:",ZeroArray)

#np.ones to create an array containing 1s
OneArray = np.ones(5)
print("Array containing ones:",OneArray)

#Creating empty array
EmptyArray = np.empty(5)
print("Empty Array:",EmptyArray)#values may vary

#Creating array with a range of values using np.arange
RangeOfValues = np.arange(6)
print("RangeOfValues:",RangeOfValues)# print values in range 0 - (n-1)

#To create array with evenly spaced numbers 
#first number, last number, and the step size
InRange = np.arange(3,20,3)
print("Evenly spaced numbers:",InRange)

# np.linspace() to create an array with values that are spaced linearly in a specified interval
IntervalArray = np.linspace(0, 20, num=5)
print("Array with interval:",IntervalArray)

#using dtype keyword to change the default datatype that is float
x = np.ones(2, dtype=np.int64)
print(x)







At position 0: 1
At position 0: [1, 2, 3, 4, 5]
First element at pos 0: 1
Array containing zeros: [0. 0. 0. 0. 0.]
Array containing ones: [1. 1. 1. 1. 1.]
Empty Array: [1. 1. 1. 1. 1.]
RangeOfValues: [0 1 2 3 4 5]
Evenly spaced numbers: [ 3  6  9 12 15 18]
Array with interval: [ 0.  5. 10. 15. 20.]
[1 1]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


Adding, removing, and sorting elements

In [44]:
#Sorting 
OriginalArray = np.array([9,4,1,6,3,7,0,2,8,5])
print("Original Array:",OriginalArray)
SortedArray = np.sort(OriginalArray)
print("SortedArray",SortedArray)

dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Achyut', 2.0, 13), ('Shipra', 1.9, 28),
          ('Surbhi', 1.7, 28)]
a = np.array(values, dtype=dtype)
SortIt = np.sort(a, order='age')
print("Sorted according to age:",SortIt)

#Sort by age, then height if ages are equal
SortHeight = np.sort(a, order=['age', 'height'])
print("Sorted according to age and height:",SortHeight)

#Lexsort
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
print("LexSort example 1:",ind)
[surnames[i] + ", " + first_names[i] for i in ind]

a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
print("LexSort example 2:",ind)


#argsort
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
print("Argsort Example1:")
[(a[i],b[i]) for i in np.argsort(a)]






Original Array: [9 4 1 6 3 7 0 2 8 5]
SortedArray [0 1 2 3 4 5 6 7 8 9]
Sorted according to age: [(b'Achyut', 2. , 13) (b'Shipra', 1.9, 28) (b'Surbhi', 1.7, 28)]
Sorted according to age and height: [(b'Achyut', 2. , 13) (b'Surbhi', 1.7, 28) (b'Shipra', 1.9, 28)]
LexSort example 1: [1 2 0]
LexSort example 2: [2 0 4 6 5 3 1]
Argsort Example1:


[(1, 9), (1, 0), (3, 0), (4, 4), (4, 2), (4, 1), (5, 4)]

In [46]:
x = np.array([3, 1, 2])
print("Argsort Example2:",np.argsort(x))

Argsort Example2: [1 2 0]


In [54]:
#Partition sort
a = np.array([3, 4, 2, 1])
print("Partition sort:",np.partition(a, 3))

Partition sort: [2 1 3 4]


In [62]:
#Searchsort
print("Searchsort:",np.searchsorted([1,2,3,4,5], 4))#returns index of searched element
print("Searchsort:",np.searchsorted([1,2,3,4,5], 1, side='right'))
print("Searchsort:",np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3]))

Searchsort: 3
Searchsort: 1
Searchsort: [0 5 1 2]


In [67]:
#Concatenate
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
print("Concatenate1:",np.concatenate((a, a2)))

x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[5, 6]])
print("Concatenate2:",np.concatenate((x1,x2), axis=0))


Concatenate1: [3 4 2 1 5 6 7 8]
Concatenate2: [[1 2]
 [3 4]
 [5 6]]


Shape and size of an array

In [70]:
array_ex = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print("Dimensions of array:",array_ex.ndim)
print("Size of array:",array_ex.size)
print("Shape of array:",array_ex.shape)


Dimensions of array: 3
Size of array: 24
Shape of array: (3, 2, 4)


In [72]:
d = np.arange(6)
print(d)
dd = d.reshape(3, 2)
print("Reshaped1:",dd)
dd = d.reshape(2, 3)
print("Reshaped2:",dd)


[0 1 2 3 4 5]
Reshaped1: [[0 1]
 [2 3]
 [4 5]]
Reshaped2: [[0 1 2]
 [3 4 5]]


Convert a 1D array into a 2D array

In [77]:
e = np.array([1, 2, 3, 4, 5, 6])
print(e.shape)
e2 = e[np.newaxis, :]
print(e2.shape)

#for row 
row_vector = a[np.newaxis, :]
print("Axis along the first dimension",row_vector.shape)
#for column
col_vector = a[:, np.newaxis]
print("Axis along the second dimension",col_vector.shape)

(6,)
(1, 6)
Axis along the first dimension (1, 6)
Axis along the second dimension (6, 1)


Indexing and slicing

In [83]:
data = np.array([1, 2, 3])
print(data[0])
print(data[0:2])
print(data[1:])
print(data[-2:])


1
[1 2]
[2 3]
[2 3]


In [89]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 7])#prints values less than7
five_up = (a >= 5)
print(a[five_up])#prints values greater than 5
divisible_by_2 = a[a%2==0]
print(divisible_by_2)#print values divisible by 2
c = a[(a > 2) & (a < 11)]#2 conditions
print(c)#prints values greater than 2 and less than 11
five_up = (a > 5) | (a == 5)#use of | or 
print(five_up)#prints values greater than 5 or equal to 5

[1 2 3 4 5 6]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [93]:
#Use of np.nonzero()
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)
print("elements in an array that are less than 5",a[b])

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
elements in an array that are less than 5 [1 2 3 4]


In [91]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


Create an array from existing data

In [94]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print("New Array:",arr1)

New Array: [4 5 6 7 8]


Stacking of arrays

In [98]:
#stack vertically with vstack
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print("Stacked up vertically:",np.vstack((a1, a2)))

#stack horizontally with hstack
print("Stacked up horizontally:",np.hstack((a1, a2)))

Stacked up vertically: [[1 1]
 [2 2]
 [3 3]
 [4 4]]
Stacked up horizontally: [[1 1 3 3]
 [2 2 4 4]]


In [101]:
#split an array into several smaller arrays using hsplit
x = np.arange(1, 25).reshape(2, 12)
print("Array:",x)
print("Split :",np.hsplit(x, 3))#splits the array in 3 equal parts
print("Split :",np.hsplit(x, (3, 4)))#splits array after the third and fourth column

Array: [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
Split : [array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
Split : [array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [104]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
print(b1)
b1[0] = 99 #Modifies first element of b1
print(b1)

#copy
b2 = a.copy()
print(b2)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Basic array operations

In [110]:
data = np.array([1, 2])
print(data)
ones = np.ones(2, dtype=int)
print(ones)
print("Add:",data + ones)
print("Product:",data * ones)
print("Sub:",data - ones)
print("Divide:",data / data)


[1 2]
[1 1]
Add: [2 3]
Product: [1 2]
Sub: [0 1]
Divide: [1. 1.]


In [111]:
#sum()
a = np.array([1, 2, 3, 4])

print("Sum is :",a.sum())


Sum is : 10


In [116]:
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0))
print(b.sum(axis=1))


[3 3]
[2 4]


Broadcasting

In [117]:
data = np.array([1.0, 2.0])
print("Multiply whole array with 1.5:",data*1.5)

Multiply whole array with 1.5: [1.5 3. ]


More useful array operations

In [119]:
data = np.array([1.0, 2.0])
print("Max:",data.max())
print("Min:",data.min())
print("Sum:",data.sum())

Max: 2.0
Min: 1.0
Sum: 3.0


Creating matrices

In [123]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix:",data)
#Indexing and slicing operations
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print("Sum:",data + ones)

Matrix: [[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]
Sum: [[2 3]
 [4 5]]


In [128]:
print(np.ones((4, 3, 2)))
#initializing
print("initialize to 1:",np.ones(3))
print("initialize to 0:",np.zeros(3))
# the simplest way to generate random numbers
rng = np.random.default_rng(0)
print("Random :",rng.random(3))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
initialize to 1: [1. 1. 1.]
initialize to 0: [0. 0. 0.]
Random : [0.63696169 0.26978671 0.04097352]


Generating random numbers

In [137]:
print("Generate Random:",rng.integers(5, size=(2, 4)))
#np.unique to print the unique values
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print("Unique Values:",unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print("indices of unique values:",indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print("occurrence_count",occurrence_count)#to get the frequency count of unique values

# unique in arrays
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print("Unique Values:",unique_values)
unique_rows = np.unique(a_2d, axis=0)
print("Unique rows:",unique_rows)

Generate Random: [[1 1 2 2]
 [3 4 0 4]]
Unique Values: [11 12 13 14 15 16 17 18 19 20]
indices of unique values: [ 0  2  3  4  5  6  7 12 13 14]
occurrence_count [3 2 2 2 1 1 1 1 1 1]
Unique Values: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Unique rows: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Transposing and reshaping a matrix

In [140]:
#Reshaping
arr = np.arange(6).reshape((2, 3))
print("Array is:",arr)
print("Transpose:",arr.transpose())
print("Transpose:",arr.T)

Array is: [[0 1 2]
 [3 4 5]]
Transpose: [[0 3]
 [1 4]
 [2 5]]
Transpose: [[0 3]
 [1 4]
 [2 5]]


How to reverse an array

In [148]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("original array:",arr)
reversed_arr = np.flip(arr)
print("Reversed Array: ", reversed_arr)

#Reversing a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print("Reversed 2d Array: ",reversed_arr)

#Reversing  all row
reversed_arr_rows = np.flip(arr_2d, axis=0)
print("Reversing row:",reversed_arr_rows)
##Reversing  all column
reversed_arr_columns = np.flip(arr_2d, axis=1)
print("Reversing column:",reversed_arr_columns)
#Reversing   row 1
arr_2d[1] = np.flip(arr_2d[1])
print("Reversing row 1:",arr_2d)
#Reversing   column 1
arr_2d[:,1] = np.flip(arr_2d[:,1])
print("Reversing column 1:",arr_2d)

original array: [1 2 3 4 5 6 7 8]
Reversed Array:  [8 7 6 5 4 3 2 1]
Reversed 2d Array:  [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
Reversing row: [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
Reversing column: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Reversing row 1: [[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
Reversing column 1: [[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


Reshaping and flattening multidimensional arrays

In [151]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Flatten:",x.flatten())
#When we use flatten, changes to our new array won’t change the parent array
a1 = x.flatten()
a1[0] = 99
print("Original array;",x)  
print("New array:",a1)  
#But when we use ravel, the changes we make to the new array will affect the parent array
a2 = x.ravel()
a2[0] = 98
print("Original array;",x)  
print("New array:",a2)

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original array; [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array: [99  2  3  4  5  6  7  8  9 10 11 12]
Original array; [[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array: [98  2  3  4  5  6  7  8  9 10 11 12]


How to access the docstring for more information

In [152]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [153]:
a = np.array([1, 2, 3, 4, 5, 6])
a?
# Type:            ndarray
String form:     [1 2 3 4 5 6]
Length:          6
File:            /usr/local/lib/python3.7/dist-packages/numpy/__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

How to save and load NumPy objects

In [157]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)
#np.load() to reconstruct your array
b = np.load('filename.npy')
print(b)
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)
np.loadtxt('new_file.csv')

[1 2 3 4 5 6]


array([1., 2., 3., 4., 5., 6., 7., 8.])

## 2. Consider this url : https://pythonexamples.org/numpy/, execute
# all the examples related to numpy. Write your observations.

Create One Dimensional Numpy Array

In [158]:
#using array()
a = np.array([5, 8, 12])
print(a)

[ 5  8 12]


In [160]:
#using arange()
a = np.arange(5, 14, 2)
print(a)

[ 5  7  9 11 13]


In [161]:
#using linspace()
a = np.linspace(5, 25, 4)
print(a)

[ 5.         11.66666667 18.33333333 25.        ]


2.Create Numpy Array with Random Values – numpy.random.rand()


In [162]:
#Create One-Dimensional Numpy Array with Random Values
a = np.random.rand(7)

print(a)

[0.93393263 0.11646775 0.16069037 0.63473309 0.19940644 0.80287604
 0.11068803]


In [163]:
#Create Two-Dimensional Numpy Array with Random Values
a = np.random.rand(2,4)

print(a)

[[0.52003619 0.96358107 0.36691193 0.74771831]
 [0.80162019 0.19560655 0.99198052 0.50375891]]


3. Save Array to File and Load Array from File

In [165]:
#initialize array
arr = np.array([[[11, 11, 9, 9],
                  [11, 0, 2, 0]
				 ],
	             [[10, 14, 9, 14],
                  [0, 1, 11, 11]]])

# open  binary file in write mode
file = open("arr", "wb")
# save array to the file
np.save(file, arr)
# close the file
file.close
# open the file in read binary mode
file = open("arr", "rb")
#read the file to numpy array
arr1 = np.load(file)
#close the file
print(arr1)

[[[11 11  9  9]
  [11  0  2  0]]

 [[10 14  9 14]
  [ 0  1 11 11]]]


4.Numpy Array with Zeros – numpy.zeros()

In [166]:
# Python Numpy Zeros Array – One Dimensional
a = np.zeros(8)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [169]:
#Python Numpy Zeros Array – Two Dimensional
a = np.zeros((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [170]:
#Python Numpy Zeros Array – Three Dimensional
a = np.zeros((3, 2, 4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [171]:
#Python Numpy Zeros Array with Specific Datatype
a = np.zeros(8, int)
print(a)

[0 0 0 0 0 0 0 0]


5.Get Specific Row

In [172]:
#Access a specific row of elements
arr = np.array([[[11, 11, 9, 9],
                 [11, 0, 2, 0]],
                [[10, 14, 9, 14],
                 [0, 1, 11, 11]]])
print('Array Shape: ',arr.shape)
row = arr[0, :, 1]
print('Desired Row of Elements: ', row)

Array Shape:  (2, 2, 4)
Desired Row of Elements:  [11  0]


In [173]:
#Access a Specific Row or Column in 2D Numpy Array
arr = np.array([[11, 11, 9, 9],
                [11,  0, 2, 0]])
print('Array\n',arr)
row = arr[1, :]
print('arr[1, :] : ', row)
row = arr[:, 2]
print('arr[:, 2] : ', row)

Array
 [[11 11  9  9]
 [11  0  2  0]]
arr[1, :] :  [11  0  2  0]
arr[:, 2] :  [9 2]


6.Get Array Shape


In [174]:
#Get Shape of Multi-Dimensional Numpy Array
arr = np.array([[[11, 11, 9, 9],
                  [11, 0, 2, 0]
				 ],
	             [[10, 14, 9, 14],
                  [0, 1, 11, 11]]])
shape = arr.shape
print(shape)

(2, 2, 4)


In [175]:
#Get Shape of 2D Numpy Array
arr = np.array([[11, 11, 9, 9],
                  [11, 0, 2, 0]])
shape = arr.shape
print(shape)

(2, 4)


In [176]:
#Get Shape of 1-Dimensional Numpy Array
arr = np.array([11, 11, 9, 9])
# get array shape
shape = arr.shape
print(shape)

(4,)


7. Iterate over Array

In [177]:
a = (np.arange(8)*2).reshape(2,4)
print("The array\n",a)
print("\nIterating over all the elemnets of array")
for x in np.nditer(a):
	print(x, end=' ')

The array
 [[ 0  2  4  6]
 [ 8 10 12 14]]

Iterating over all the elemnets of array
0 2 4 6 8 10 12 14 

8.Duplicate or Copy Array Data to Another Array

In [179]:
#using copy()
a = np.array([[8, 2, 3],
              [4, 7, 6]])
b = a.copy()

# modify a
a[1, 2] = 13

# check if b has remained the same
print('a\n',a)
print('\nb\n',b)

a
 [[ 8  2  3]
 [ 4  7 13]]

b
 [[8 2 3]
 [4 7 6]]


In [180]:
#if we use assignment operator
a = np.array([[8, 2, 3],
              [4, 7, 6]])
b = a

# modify a
a[1, 2] = 13

# check if b has remained the same
print('a\n',a)
print('\nb\n',b)

a
 [[ 8  2  3]
 [ 4  7 13]]

b
 [[ 8  2  3]
 [ 4  7 13]]


9.Stack Arrays Vertically

In [181]:
# numpy.vstack() with two 2D arrays
A = np.array([[2, 1], [5, 4]])
B = np.array([[3, 4], [7, 8]])
output = np.vstack((A, B))
print(output)


[[2 1]
 [5 4]
 [3 4]
 [7 8]]


In [182]:
#Vertically Stack 1D Numpy Arrays
A = np.array([2, 1, 5, 4])
B = np.array([3, 4, 7, 8])
C = np.array([8, 6, 0, 3])
output = np.vstack((A, B, C))
print(output)

[[2 1 5 4]
 [3 4 7 8]
 [8 6 0 3]]


10.Stack Arrays Horizontally

In [183]:
A = np.array([2, 1, 5, 4])
B = np.array([3, 4, 7, 8])
C = np.array([8, 6, 0, 3])
output = np.hstack((A, B, C))
print(output)

[2 1 5 4 3 4 7 8 8 6 0 3]


11.Dot Product

In [184]:
#Numpy Dot Product of Scalars
a = 3 
b = 4
output = np.dot(a,b)
print(output)

12


In [185]:
#Numpy Dot Product of 1D Arrays (Vectors)
A = np.array([2, 1, 5, 4])
B = np.array([3, 4, 7, 8])
output = np.dot(A, B)
print(output)

77


In [186]:
# Numpy Dot Product of 2-D Arrays (Matrix)
A = np.array([[2, 1], [5, 4]])
B = np.array([[3, 4], [7, 8]])
output = np.dot(A, B)
print(output)

[[13 16]
 [43 52]]


12.Cross Product

In [187]:
#Cross Product of Numpy Arrays
A = np.array([2, 3])
B = np.array([1, 7])
output = np.cross(A, B)
print(output)

11


In [188]:
#Cross Product of Numpy Arrays in 3D
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
output = np.cross(A, B)
print(output)

[20 -4 -3]


How to get unique items and counts